/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ide;

import ut2j.m1ice.ide.AbstractStateMachineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StateMachineIdeModule extends AbstractStateMachineIdeModule {
}
