/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ut2j.m1ice.StateMachineRuntimeModule;
import ut2j.m1ice.StateMachineStandaloneSetup;
import ut2j.m1ice.ide.StateMachineIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StateMachineIdeSetup extends StateMachineStandaloneSetup {
  @Override
  public Injector createInjector() {
    StateMachineRuntimeModule _stateMachineRuntimeModule = new StateMachineRuntimeModule();
    StateMachineIdeModule _stateMachineIdeModule = new StateMachineIdeModule();
    return Guice.createInjector(Modules2.mixin(_stateMachineRuntimeModule, _stateMachineIdeModule));
  }
}
