/*
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateMachineScopeProvider extends DelegatingScopeProvider {
}
