/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice;

import ut2j.m1ice.AbstractStateMachineRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateMachineRuntimeModule extends AbstractStateMachineRuntimeModule {
}
