/*
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StateMachineUiModule extends AbstractStateMachineUiModule {
}
