/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;
import ut2j.m1ice.services.StateMachineGrammarAccess;

@SuppressWarnings("all")
public class StateMachineFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private StateMachineGrammarAccess _stateMachineGrammarAccess;
}
