/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ut2j.m1ice.ui.AbstractStateMachineUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateMachineUiModule extends AbstractStateMachineUiModule {
  public StateMachineUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
