/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.scoping;

import ut2j.m1ice.scoping.AbstractStateMachineScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class StateMachineScopeProvider extends AbstractStateMachineScopeProvider {
}
