/*
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StateMachineAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ut2j/m1ice/parser/antlr/internal/InternalStateMachine.tokens");
	}
}
