/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.validation;

import ut2j.m1ice.validation.AbstractStateMachineValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StateMachineValidator extends AbstractStateMachineValidator {
}
