/**
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ui.contentassist;

import ut2j.m1ice.ui.contentassist.AbstractStateMachineProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StateMachineProposalProvider extends AbstractStateMachineProposalProvider {
}
