/*
 * generated by Xtext 2.14.0
 */
package ut2j.m1ice.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ut2j.m1ice.StateMachine.ui.internal.StateMachineActivator;

public class StateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StateMachineActivator.getInstance().getInjector("ut2j.m1ice.StateMachine");
	}

}
